/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class winjcom_WinjcomPort */

#ifndef _Included_winjcom_WinjcomPort
#define _Included_winjcom_WinjcomPort
#ifdef __cplusplus
extern "C" {
#endif
#undef winjcom_WinjcomPort_DATABITS_5
#define winjcom_WinjcomPort_DATABITS_5 5L
#undef winjcom_WinjcomPort_DATABITS_6
#define winjcom_WinjcomPort_DATABITS_6 6L
#undef winjcom_WinjcomPort_DATABITS_7
#define winjcom_WinjcomPort_DATABITS_7 7L
#undef winjcom_WinjcomPort_DATABITS_8
#define winjcom_WinjcomPort_DATABITS_8 8L
#undef winjcom_WinjcomPort_PARITY_NONE
#define winjcom_WinjcomPort_PARITY_NONE 0L
#undef winjcom_WinjcomPort_PARITY_ODD
#define winjcom_WinjcomPort_PARITY_ODD 1L
#undef winjcom_WinjcomPort_PARITY_EVEN
#define winjcom_WinjcomPort_PARITY_EVEN 2L
#undef winjcom_WinjcomPort_PARITY_MARK
#define winjcom_WinjcomPort_PARITY_MARK 3L
#undef winjcom_WinjcomPort_PARITY_SPACE
#define winjcom_WinjcomPort_PARITY_SPACE 4L
#undef winjcom_WinjcomPort_STOPBITS_1
#define winjcom_WinjcomPort_STOPBITS_1 1L
#undef winjcom_WinjcomPort_STOPBITS_2
#define winjcom_WinjcomPort_STOPBITS_2 2L
#undef winjcom_WinjcomPort_STOPBITS_1_5
#define winjcom_WinjcomPort_STOPBITS_1_5 3L
#undef winjcom_WinjcomPort_FLOWCONTROL_NONE
#define winjcom_WinjcomPort_FLOWCONTROL_NONE 0L
#undef winjcom_WinjcomPort_FLOWCONTROL_RTSCTS_IN
#define winjcom_WinjcomPort_FLOWCONTROL_RTSCTS_IN 1L
#undef winjcom_WinjcomPort_FLOWCONTROL_RTSCTS_OUT
#define winjcom_WinjcomPort_FLOWCONTROL_RTSCTS_OUT 2L
#undef winjcom_WinjcomPort_FLOWCONTROL_XONXOFF_IN
#define winjcom_WinjcomPort_FLOWCONTROL_XONXOFF_IN 4L
#undef winjcom_WinjcomPort_FLOWCONTROL_XONXOFF_OUT
#define winjcom_WinjcomPort_FLOWCONTROL_XONXOFF_OUT 8L
#undef winjcom_WinjcomPort_DCB_BAUDRATE
#define winjcom_WinjcomPort_DCB_BAUDRATE 1L
#undef winjcom_WinjcomPort_DCB_DATABITS
#define winjcom_WinjcomPort_DCB_DATABITS 2L
#undef winjcom_WinjcomPort_DCB_STOPBITS
#define winjcom_WinjcomPort_DCB_STOPBITS 3L
#undef winjcom_WinjcomPort_DCB_PARITY
#define winjcom_WinjcomPort_DCB_PARITY 4L
#undef winjcom_WinjcomPort_DCB_FLOWCONTROL
#define winjcom_WinjcomPort_DCB_FLOWCONTROL 5L
#undef winjcom_WinjcomPort_ESC_SETRTS
#define winjcom_WinjcomPort_ESC_SETRTS 3L
#undef winjcom_WinjcomPort_ESC_CLRRTS
#define winjcom_WinjcomPort_ESC_CLRRTS 4L
#undef winjcom_WinjcomPort_ESC_SETDTR
#define winjcom_WinjcomPort_ESC_SETDTR 5L
#undef winjcom_WinjcomPort_ESC_CLRDTR
#define winjcom_WinjcomPort_ESC_CLRDTR 6L
#undef winjcom_WinjcomPort_ESC_SETBREAK
#define winjcom_WinjcomPort_ESC_SETBREAK 8L
#undef winjcom_WinjcomPort_ESC_CLRBREAk
#define winjcom_WinjcomPort_ESC_CLRBREAk 9L
#undef winjcom_WinjcomPort_MS_CTS_ON
#define winjcom_WinjcomPort_MS_CTS_ON 16L
#undef winjcom_WinjcomPort_MS_DSR_ON
#define winjcom_WinjcomPort_MS_DSR_ON 32L
#undef winjcom_WinjcomPort_MS_RING_ON
#define winjcom_WinjcomPort_MS_RING_ON 64L
#undef winjcom_WinjcomPort_MS_RLSD_ON
#define winjcom_WinjcomPort_MS_RLSD_ON 128L
#undef winjcom_WinjcomPort_EV_RXCHAR
#define winjcom_WinjcomPort_EV_RXCHAR 1L
#undef winjcom_WinjcomPort_EV_CTS
#define winjcom_WinjcomPort_EV_CTS 8L
#undef winjcom_WinjcomPort_EV_TXEMPTY
#define winjcom_WinjcomPort_EV_TXEMPTY 4L
#undef winjcom_WinjcomPort_EV_DSR
#define winjcom_WinjcomPort_EV_DSR 16L
#undef winjcom_WinjcomPort_EV_BREAK
#define winjcom_WinjcomPort_EV_BREAK 64L
#undef winjcom_WinjcomPort_EV_ERR
#define winjcom_WinjcomPort_EV_ERR 128L
#undef winjcom_WinjcomPort_EV_RING
#define winjcom_WinjcomPort_EV_RING 256L
#undef winjcom_WinjcomPort_EV_RLSD
#define winjcom_WinjcomPort_EV_RLSD 32L
#undef winjcom_WinjcomPort_COMSTAT_cbInQue
#define winjcom_WinjcomPort_COMSTAT_cbInQue 1L
/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_winjcom_WinjcomPort_nativeOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeSetSerialPortParams
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_winjcom_WinjcomPort_nativeSetSerialPortParams
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeGetPortParam
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_winjcom_WinjcomPort_nativeGetPortParam
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeSetPortParam
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_winjcom_WinjcomPort_nativeSetPortParam
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeSetCommTimeouts
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_winjcom_WinjcomPort_nativeSetCommTimeouts
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeGetReceiveTotalTimeoutConstant
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_winjcom_WinjcomPort_nativeGetReceiveTotalTimeoutConstant
  (JNIEnv *, jobject, jlong);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeSendEscape
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_winjcom_WinjcomPort_nativeSendEscape
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeGetModemStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_winjcom_WinjcomPort_nativeGetModemStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeNotifyEnable
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_winjcom_WinjcomPort_nativeNotifyEnable
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeWriteArray
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_winjcom_WinjcomPort_nativeWriteArray
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativePurgeComm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_winjcom_WinjcomPort_nativePurgeComm
  (JNIEnv *, jobject, jlong);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeClearCommError
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_winjcom_WinjcomPort_nativeClearCommError
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeReadArray
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_winjcom_WinjcomPort_nativeReadArray
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_winjcom_WinjcomPort_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     winjcom_WinjcomPort
 * Method:    nativeGetCommEvent
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_winjcom_WinjcomPort_nativeGetCommEvent
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class winjcom_WinjcomPort_MonitorThread */

#ifndef _Included_winjcom_WinjcomPort_MonitorThread
#define _Included_winjcom_WinjcomPort_MonitorThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class winjcom_WinjcomIdentifier */

#ifndef _Included_winjcom_WinjcomIdentifier
#define _Included_winjcom_WinjcomIdentifier
#ifdef __cplusplus
extern "C" {
#endif
#undef winjcom_WinjcomIdentifier_DEBUG_INIT
#define winjcom_WinjcomIdentifier_DEBUG_INIT 1L
#undef winjcom_WinjcomIdentifier_DEBUG_TEST_PORT
#define winjcom_WinjcomIdentifier_DEBUG_TEST_PORT 2L
#undef winjcom_WinjcomIdentifier_DEBUG_ERRORS
#define winjcom_WinjcomIdentifier_DEBUG_ERRORS 4L
#undef winjcom_WinjcomIdentifier_DEBUG_OPEN_PORT
#define winjcom_WinjcomIdentifier_DEBUG_OPEN_PORT 8L
#undef winjcom_WinjcomIdentifier_DEBUG_WRITE
#define winjcom_WinjcomIdentifier_DEBUG_WRITE 16L
#undef winjcom_WinjcomIdentifier_DEBUG_READ
#define winjcom_WinjcomIdentifier_DEBUG_READ 32L
#undef winjcom_WinjcomIdentifier_DEBUG_COMMEVENT
#define winjcom_WinjcomIdentifier_DEBUG_COMMEVENT 64L
#undef winjcom_WinjcomIdentifier_DEBUG_POPARAMS
#define winjcom_WinjcomIdentifier_DEBUG_POPARAMS 128L
#undef winjcom_WinjcomIdentifier_DEBUG_CLOSE_PORT
#define winjcom_WinjcomIdentifier_DEBUG_CLOSE_PORT 256L
/*
 * Class:     winjcom_WinjcomIdentifier
 * Method:    nativeInitialize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_winjcom_WinjcomIdentifier_nativeInitialize
  (JNIEnv *, jobject, jint);

/*
 * Class:     winjcom_WinjcomIdentifier
 * Method:    nativeIsPortPresent
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_winjcom_WinjcomIdentifier_nativeIsPortPresent
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class winjcom_SerialPort */

#ifndef _Included_winjcom_SerialPort
#define _Included_winjcom_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
#undef winjcom_SerialPort_DATABITS_5
#define winjcom_SerialPort_DATABITS_5 5L
#undef winjcom_SerialPort_DATABITS_6
#define winjcom_SerialPort_DATABITS_6 6L
#undef winjcom_SerialPort_DATABITS_7
#define winjcom_SerialPort_DATABITS_7 7L
#undef winjcom_SerialPort_DATABITS_8
#define winjcom_SerialPort_DATABITS_8 8L
#undef winjcom_SerialPort_PARITY_NONE
#define winjcom_SerialPort_PARITY_NONE 0L
#undef winjcom_SerialPort_PARITY_ODD
#define winjcom_SerialPort_PARITY_ODD 1L
#undef winjcom_SerialPort_PARITY_EVEN
#define winjcom_SerialPort_PARITY_EVEN 2L
#undef winjcom_SerialPort_PARITY_MARK
#define winjcom_SerialPort_PARITY_MARK 3L
#undef winjcom_SerialPort_PARITY_SPACE
#define winjcom_SerialPort_PARITY_SPACE 4L
#undef winjcom_SerialPort_STOPBITS_1
#define winjcom_SerialPort_STOPBITS_1 1L
#undef winjcom_SerialPort_STOPBITS_2
#define winjcom_SerialPort_STOPBITS_2 2L
#undef winjcom_SerialPort_STOPBITS_1_5
#define winjcom_SerialPort_STOPBITS_1_5 3L
#undef winjcom_SerialPort_FLOWCONTROL_NONE
#define winjcom_SerialPort_FLOWCONTROL_NONE 0L
#undef winjcom_SerialPort_FLOWCONTROL_RTSCTS_IN
#define winjcom_SerialPort_FLOWCONTROL_RTSCTS_IN 1L
#undef winjcom_SerialPort_FLOWCONTROL_RTSCTS_OUT
#define winjcom_SerialPort_FLOWCONTROL_RTSCTS_OUT 2L
#undef winjcom_SerialPort_FLOWCONTROL_XONXOFF_IN
#define winjcom_SerialPort_FLOWCONTROL_XONXOFF_IN 4L
#undef winjcom_SerialPort_FLOWCONTROL_XONXOFF_OUT
#define winjcom_SerialPort_FLOWCONTROL_XONXOFF_OUT 8L
#ifdef __cplusplus
}
#endif
#endif
